"""initial schema

Revision ID: df2b49f878ea
Revises: 
Create Date: 2026-08-26 14:26:18.486922
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=True),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_occurred_at'), 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('controllers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hydrawise_controller_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_successful_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_controllers'))
    )
    op.create_index(op.f('ix_controllers_hydrawise_controller_id'), 'controllers', ['hydrawise_controller_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'VIEWER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_epoch', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('data_gaps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('controller_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Enum('NETWORK', 'API_429', 'API_ERROR', 'INVALID_PAYLOAD', 'WORKER_DOWN', name='gap_reason'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('may_affect_runtime', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], name=op.f('fk_data_gaps_controller_id_controllers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_gaps'))
    )
    op.create_index('ix_data_gaps_controller_started', 'data_gaps', ['controller_id', 'started_at'], unique=False)
    op.create_table('monthly_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('controller_id', sa.UUID(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'FINAL', 'SENT', 'FAILED', name='report_status'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_zone_runtime_seconds', sa.BigInteger(), nullable=False),
    sa.Column('pump_union_runtime_seconds', sa.BigInteger(), nullable=False),
    sa.Column('total_water_liters_estimate', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_water_liters_min', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('total_water_liters_max', sa.Numeric(precision=16, scale=2), nullable=False),
    sa.Column('energy_kwh_estimate', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('data_coverage_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('html_path', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.Text(), nullable=True),
    sa.Column('public_token_hash', sa.String(length=64), nullable=True),
    sa.Column('public_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], name=op.f('fk_monthly_reports_controller_id_controllers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_monthly_reports')),
    sa.UniqueConstraint('controller_id', 'month', name='monthly_reports_controller_month')
    )
    op.create_index(op.f('ix_monthly_reports_month'), 'monthly_reports', ['month'], unique=False)
    op.create_index(op.f('ix_monthly_reports_public_token_hash'), 'monthly_reports', ['public_token_hash'], unique=False)
    op.create_table('poll_samples',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('controller_id', sa.UUID(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_epoch', sa.BigInteger(), nullable=True),
    sa.Column('nextpoll_seconds', sa.Integer(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], name=op.f('fk_poll_samples_controller_id_controllers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_poll_samples'))
    )
    op.create_index('ix_poll_samples_controller_observed', 'poll_samples', ['controller_id', 'observed_at'], unique=False)
    op.create_index(op.f('ix_poll_samples_observed_at'), 'poll_samples', ['observed_at'], unique=False)
    op.create_table('pump_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('controller_id', sa.UUID(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('rated_hp', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rated_kw', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('estimated_input_kw', sa.Numeric(precision=8, scale=3), nullable=False),
    sa.Column('voltage_min', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('voltage_max', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rated_current_a', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('frequency_hz', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('head_min_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('head_max_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('flow_min_lpm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('flow_default_lpm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('flow_max_lpm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('well_depth_m', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], name=op.f('fk_pump_profiles_controller_id_controllers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pump_profiles')),
    sa.UniqueConstraint('controller_id', name=op.f('uq_pump_profiles_controller_id'))
    )
    op.create_table('zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('controller_id', sa.UUID(), nullable=False),
    sa.Column('hydrawise_relay_id', sa.BigInteger(), nullable=False),
    sa.Column('physical_number', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('display_name_ar', sa.String(length=160), nullable=True),
    sa.Column('flow_rate_lpm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('flow_min_lpm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('flow_max_lpm', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('calibration_method', sa.Enum('DEFAULT', 'MANUAL', 'FLOW_METER', 'PUMP_CURVE', name='calibration_method'), nullable=False),
    sa.Column('calibrated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('missing_sync_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], name=op.f('fk_zones_controller_id_controllers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zones')),
    sa.UniqueConstraint('controller_id', 'hydrawise_relay_id', name='zones_controller_relay')
    )
    op.create_index(op.f('ix_zones_hydrawise_relay_id'), 'zones', ['hydrawise_relay_id'], unique=False)
    op.create_table('notification_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('OPENWA', 'EMAIL', name='delivery_channel'), nullable=False),
    sa.Column('recipient_masked', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='delivery_status'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['monthly_reports.id'], name=op.f('fk_notification_deliveries_report_id_monthly_reports'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('report_id', 'channel', 'recipient_masked', name='notification_idempotency')
    )
    op.create_table('zone_runtime_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runtime_seconds', sa.Integer(), nullable=True),
    sa.Column('start_sample_id', sa.BigInteger(), nullable=True),
    sa.Column('end_sample_id', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.Enum('API_OBSERVED', 'API_INFERRED', 'MANUAL_IMPORT', 'MANUAL_ADJUSTMENT', name='event_source'), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='event_confidence'), nullable=False),
    sa.Column('planned_runtime_seconds', sa.Integer(), nullable=True),
    sa.Column('last_remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('last_running_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('water_liters_estimate', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('flow_rate_lpm_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('flow_min_lpm_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('flow_max_lpm_snapshot', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_adjusted', sa.Boolean(), nullable=False),
    sa.Column('adjustment_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ended_at IS NULL OR ended_at >= started_at', name=op.f('ck_zone_runtime_events_ended_after_started')),
    sa.CheckConstraint('runtime_seconds IS NULL OR runtime_seconds >= 0', name=op.f('ck_zone_runtime_events_runtime_non_negative')),
    sa.ForeignKeyConstraint(['end_sample_id'], ['poll_samples.id'], name=op.f('fk_zone_runtime_events_end_sample_id_poll_samples'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['start_sample_id'], ['poll_samples.id'], name=op.f('fk_zone_runtime_events_start_sample_id_poll_samples'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], name=op.f('fk_zone_runtime_events_zone_id_zones'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_zone_runtime_events'))
    )
    op.create_index(op.f('ix_zone_runtime_events_started_at'), 'zone_runtime_events', ['started_at'], unique=False)
    op.create_index('ix_zone_runtime_events_zone_started', 'zone_runtime_events', ['zone_id', 'started_at'], unique=False)
    op.create_index('uq_zone_runtime_events_open_zone', 'zone_runtime_events', ['zone_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_zone_runtime_events_open_zone', table_name='zone_runtime_events', postgresql_where=sa.text('ended_at IS NULL'))
    op.drop_index('ix_zone_runtime_events_zone_started', table_name='zone_runtime_events')
    op.drop_index(op.f('ix_zone_runtime_events_started_at'), table_name='zone_runtime_events')
    op.drop_table('zone_runtime_events')
    op.drop_table('notification_deliveries')
    op.drop_index(op.f('ix_zones_hydrawise_relay_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_table('pump_profiles')
    op.drop_index(op.f('ix_poll_samples_observed_at'), table_name='poll_samples')
    op.drop_index('ix_poll_samples_controller_observed', table_name='poll_samples')
    op.drop_table('poll_samples')
    op.drop_index(op.f('ix_monthly_reports_public_token_hash'), table_name='monthly_reports')
    op.drop_index(op.f('ix_monthly_reports_month'), table_name='monthly_reports')
    op.drop_table('monthly_reports')
    op.drop_index('ix_data_gaps_controller_started', table_name='data_gaps')
    op.drop_table('data_gaps')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_controllers_hydrawise_controller_id'), table_name='controllers')
    op.drop_table('controllers')
    op.drop_index(op.f('ix_audit_logs_occurred_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###

    # أنواع ENUM لا تُحذف مع الجداول التي أنشأتها؛ بدون هذا يفشل الترقية
    # التالية بـ"type already exists" وتصبح الترحيلة غير قابلة للعكس فعليًا.
    for enum_name in (
        'calibration_method',
        'event_source',
        'event_confidence',
        'gap_reason',
        'report_status',
        'delivery_channel',
        'delivery_status',
        'user_role',
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))
